dist: focal
language: node_js

addons:
  sonarcloud:
    organization: rafiandria23

node_js:
  - lts/*

install:
  - yarn global add lerna
  - yarn install --frozen-lockfile

script:
  - yarn test
  - sonar-scanner
